# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [ staging, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2.2.0
      with:
        projectBaseDir: .
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/iron
    - run: npm ci
    - run: npm run test
