# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test CI

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    environment: dev
    env:
      PORT: ${{ vars.PORT}}
      JWT_SECRET: ${{ vars.JWT_SECRET}}
      BASE_API_AUDIENCE: ${{vars.BASE_API_AUDIENCE}}
      BASE_API_ISSUER: ${{vars.BASE_API_ISSUER}}
      APP_ENV: ${{vars.APP_ENV}}
      USER_ROLE_ID: ${{vars.USER_ROLE_ID}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
      - run: npm ci
      - run: npx prisma generate --schema=apps/base-api/prisma/schema.prisma
      - run: npx nx run-many --target=lint --parallel=5 --base=origin/staging --verbose
      - run: npx nx run-many --target=build --parallel=5 --base=origin/staging --verbose
      - run: npx nx run-many --target=test --parallel=5 --codeCoverage --verbose

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
